name: fossa
on:
  push:
    branches:
      - main
      - release-*
      - feature/*
    tags:
      - v*
  pull_request:
    branches:
      - main
      - release-*
      - feature/*
  workflow_dispatch: {}
jobs:
  fossa-scan:
    runs-on: ubuntu-latest
    env:
      FOSSA_API_KEY: 41d62718405eaeefefefae7ef9add8c0 # This is a push-only token that is safe to be exposed.
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Run FOSSA Scan"
        uses: fossas/fossa-action@main # Use a specific version if locking is preferred
        with:
          api-key: ${{ env.FOSSA_API_KEY }}

      - name: "Run FOSSA Test"
        uses: fossas/fossa-action@main # Use a specific version if locking is preferred
        with:
          api-key: ${{ env.FOSSA_API_KEY }}
          run-tests: true
