name: license

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  add-license:
    runs-on: ubuntu-latest
    steps:
      - name: Fix License Header
        uses: apache/skywalking-eyes/header@main
        with:
          mode: fix
      - name: Apply Changes
        uses: EndBug/add-and-commit@v4
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          author_name: License Bot
          author_email: license_bot@github.com
          message: 'Automatic application of license header'
